/**
 * ============================================================================
 * DATABASE TYPES — generated from the schema in supabase/migrations
 * ============================================================================
 * Do not edit by hand. Once you have a real Supabase project, regenerate with:
 *
 *     npm run db:types
 *
 * Timestamps are typed as `string` because PostgREST returns ISO-8601 text.
 * ============================================================================
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      account_credits: {
        Row: {
          id: string;
          business_id: string;
          client_id: string;
          amount_cents: number;
          balance_after: number;
          reason: string;
          order_id: string | null;
          referral_id: string | null;
          expires_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          client_id: string;
          amount_cents: number;
          balance_after: number;
          reason: string;
          order_id?: string | null;
          referral_id?: string | null;
          expires_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          client_id?: string;
          amount_cents?: number;
          balance_after?: number;
          reason?: string;
          order_id?: string | null;
          referral_id?: string | null;
          expires_at?: string | null;
          created_at?: string;
        };
      };
      addons: {
        Row: {
          id: string;
          business_id: string;
          name: string;
          description: string | null;
          duration_min: number;
          price_cents: number;
          member_price_cents: number | null;
          cost_cents: number;
          taxable: boolean;
          image_url: string | null;
          sort_order: number;
          active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          name: string;
          description?: string | null;
          duration_min?: number;
          price_cents?: number;
          member_price_cents?: number | null;
          cost_cents?: number;
          taxable?: boolean;
          image_url?: string | null;
          sort_order?: number;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          name?: string;
          description?: string | null;
          duration_min?: number;
          price_cents?: number;
          member_price_cents?: number | null;
          cost_cents?: number;
          taxable?: boolean;
          image_url?: string | null;
          sort_order?: number;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      appointment_addons: {
        Row: {
          id: string;
          appointment_id: string;
          addon_id: string;
          name_snapshot: string;
          price_cents: number;
          duration_min: number;
          from_upsell: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          appointment_id: string;
          addon_id: string;
          name_snapshot: string;
          price_cents?: number;
          duration_min?: number;
          from_upsell?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          appointment_id?: string;
          addon_id?: string;
          name_snapshot?: string;
          price_cents?: number;
          duration_min?: number;
          from_upsell?: boolean;
          created_at?: string;
        };
      };
      appointment_busy_blocks: {
        Row: {
          id: string;
          appointment_id: string;
          business_id: string;
          staff_id: string | null;
          room_id: string | null;
          block: unknown;
        };
        Insert: {
          id?: string;
          appointment_id: string;
          business_id: string;
          staff_id?: string | null;
          room_id?: string | null;
          block: unknown;
        };
        Update: {
          id?: string;
          appointment_id?: string;
          business_id?: string;
          staff_id?: string | null;
          room_id?: string | null;
          block?: unknown;
        };
      };
      appointments: {
        Row: {
          id: string;
          business_id: string;
          location_id: string;
          client_id: string;
          staff_id: string | null;
          service_id: string;
          room_id: string | null;
          starts_at: string;
          ends_at: string;
          blocks_at: string;
          blocks_until: string;
          gap_starts_at: string | null;
          gap_ends_at: string | null;
          duration_min: number;
          status: Database["public"]["Enums"]["appointment_status"];
          source: Database["public"]["Enums"]["booking_source"];
          price_cents: number;
          addons_cents: number;
          discount_cents: number;
          deposit_cents: number;
          deposit_paid_at: string | null;
          deposit_payment_intent_id: string | null;
          order_id: string | null;
          membership_id: string | null;
          client_package_id: string | null;
          paid_with_credit: boolean;
          rebooked_from_id: string | null;
          rescheduled_to_id: string | null;
          reschedule_count: number;
          attributed_send_id: string | null;
          confirmed_at: string | null;
          checked_in_at: string | null;
          started_at: string | null;
          completed_at: string | null;
          cancelled_at: string | null;
          cancelled_by: string | null;
          cancellation_reason: string | null;
          cancellation_fee_cents: number;
          no_show_at: string | null;
          no_show_fee_cents: number;
          client_notes: string | null;
          internal_notes: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          location_id: string;
          client_id: string;
          staff_id?: string | null;
          service_id: string;
          room_id?: string | null;
          starts_at: string;
          ends_at: string;
          blocks_at: string;
          blocks_until: string;
          gap_starts_at?: string | null;
          gap_ends_at?: string | null;
          duration_min: number;
          status?: Database["public"]["Enums"]["appointment_status"];
          source?: Database["public"]["Enums"]["booking_source"];
          price_cents?: number;
          addons_cents?: number;
          discount_cents?: number;
          deposit_cents?: number;
          deposit_paid_at?: string | null;
          deposit_payment_intent_id?: string | null;
          order_id?: string | null;
          membership_id?: string | null;
          client_package_id?: string | null;
          paid_with_credit?: boolean;
          rebooked_from_id?: string | null;
          rescheduled_to_id?: string | null;
          reschedule_count?: number;
          attributed_send_id?: string | null;
          confirmed_at?: string | null;
          checked_in_at?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          cancelled_at?: string | null;
          cancelled_by?: string | null;
          cancellation_reason?: string | null;
          cancellation_fee_cents?: number;
          no_show_at?: string | null;
          no_show_fee_cents?: number;
          client_notes?: string | null;
          internal_notes?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          location_id?: string;
          client_id?: string;
          staff_id?: string | null;
          service_id?: string;
          room_id?: string | null;
          starts_at?: string;
          ends_at?: string;
          blocks_at?: string;
          blocks_until?: string;
          gap_starts_at?: string | null;
          gap_ends_at?: string | null;
          duration_min?: number;
          status?: Database["public"]["Enums"]["appointment_status"];
          source?: Database["public"]["Enums"]["booking_source"];
          price_cents?: number;
          addons_cents?: number;
          discount_cents?: number;
          deposit_cents?: number;
          deposit_paid_at?: string | null;
          deposit_payment_intent_id?: string | null;
          order_id?: string | null;
          membership_id?: string | null;
          client_package_id?: string | null;
          paid_with_credit?: boolean;
          rebooked_from_id?: string | null;
          rescheduled_to_id?: string | null;
          reschedule_count?: number;
          attributed_send_id?: string | null;
          confirmed_at?: string | null;
          checked_in_at?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          cancelled_at?: string | null;
          cancelled_by?: string | null;
          cancellation_reason?: string | null;
          cancellation_fee_cents?: number;
          no_show_at?: string | null;
          no_show_fee_cents?: number;
          client_notes?: string | null;
          internal_notes?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      audit_log: {
        Row: {
          id: number;
          business_id: string | null;
          actor_user_id: string | null;
          actor_staff_id: string | null;
          action: string;
          entity_type: string | null;
          entity_id: string | null;
          before: Json | null;
          after: Json | null;
          ip_address: string | null;
          user_agent: string | null;
          created_at: string;
        };
        Insert: {
          id?: number;
          business_id?: string | null;
          actor_user_id?: string | null;
          actor_staff_id?: string | null;
          action: string;
          entity_type?: string | null;
          entity_id?: string | null;
          before?: Json | null;
          after?: Json | null;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Update: {
          id?: number;
          business_id?: string | null;
          actor_user_id?: string | null;
          actor_staff_id?: string | null;
          action?: string;
          entity_type?: string | null;
          entity_id?: string | null;
          before?: Json | null;
          after?: Json | null;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
      };
      blocked_times: {
        Row: {
          id: string;
          business_id: string;
          location_id: string | null;
          starts_at: string;
          ends_at: string;
          reason: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          location_id?: string | null;
          starts_at: string;
          ends_at: string;
          reason?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          location_id?: string | null;
          starts_at?: string;
          ends_at?: string;
          reason?: string | null;
          created_at?: string;
        };
      };
      businesses: {
        Row: {
          id: string;
          slug: string;
          name: string;
          legal_name: string | null;
          vertical: string;
          timezone: string;
          currency: string;
          locale: string;
          branding: Json;
          policy: Json;
          features: Json;
          stripe_customer_id: string | null;
          stripe_account_id: string | null;
          tax_rate_bps: number;
          onboarding_completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          legal_name?: string | null;
          vertical?: string;
          timezone?: string;
          currency?: string;
          locale?: string;
          branding?: Json;
          policy?: Json;
          features?: Json;
          stripe_customer_id?: string | null;
          stripe_account_id?: string | null;
          tax_rate_bps?: number;
          onboarding_completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          legal_name?: string | null;
          vertical?: string;
          timezone?: string;
          currency?: string;
          locale?: string;
          branding?: Json;
          policy?: Json;
          features?: Json;
          stripe_customer_id?: string | null;
          stripe_account_id?: string | null;
          tax_rate_bps?: number;
          onboarding_completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      campaign_sends: {
        Row: {
          id: string;
          business_id: string;
          campaign_id: string | null;
          client_id: string;
          appointment_id: string | null;
          membership_id: string | null;
          channel: Database["public"]["Enums"]["message_channel"];
          status: Database["public"]["Enums"]["send_status"];
          to_address: string | null;
          subject: string | null;
          body: string | null;
          scheduled_for: string;
          sent_at: string | null;
          delivered_at: string | null;
          opened_at: string | null;
          clicked_at: string | null;
          failed_at: string | null;
          error: string | null;
          skip_reason: string | null;
          converted_at: string | null;
          converted_appointment_id: string | null;
          conversion_value_cents: number;
          provider_message_id: string | null;
          dedupe_key: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          campaign_id?: string | null;
          client_id: string;
          appointment_id?: string | null;
          membership_id?: string | null;
          channel: Database["public"]["Enums"]["message_channel"];
          status?: Database["public"]["Enums"]["send_status"];
          to_address?: string | null;
          subject?: string | null;
          body?: string | null;
          scheduled_for?: string;
          sent_at?: string | null;
          delivered_at?: string | null;
          opened_at?: string | null;
          clicked_at?: string | null;
          failed_at?: string | null;
          error?: string | null;
          skip_reason?: string | null;
          converted_at?: string | null;
          converted_appointment_id?: string | null;
          conversion_value_cents?: number;
          provider_message_id?: string | null;
          dedupe_key?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          campaign_id?: string | null;
          client_id?: string;
          appointment_id?: string | null;
          membership_id?: string | null;
          channel?: Database["public"]["Enums"]["message_channel"];
          status?: Database["public"]["Enums"]["send_status"];
          to_address?: string | null;
          subject?: string | null;
          body?: string | null;
          scheduled_for?: string;
          sent_at?: string | null;
          delivered_at?: string | null;
          opened_at?: string | null;
          clicked_at?: string | null;
          failed_at?: string | null;
          error?: string | null;
          skip_reason?: string | null;
          converted_at?: string | null;
          converted_appointment_id?: string | null;
          conversion_value_cents?: number;
          provider_message_id?: string | null;
          dedupe_key?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      campaigns: {
        Row: {
          id: string;
          business_id: string;
          key: string;
          name: string;
          description: string | null;
          trigger_type: Database["public"]["Enums"]["campaign_trigger"];
          config: Json;
          channel: Database["public"]["Enums"]["message_channel"];
          fallback_channel: Database["public"]["Enums"]["message_channel"] | null;
          template_key: string;
          cooldown_days: number;
          skip_if_future_booking: boolean;
          skip_if_lapsed_beyond_days: number | null;
          min_churn_risk: number;
          respect_quiet_hours: boolean;
          daily_send_cap: number | null;
          active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          key: string;
          name: string;
          description?: string | null;
          trigger_type: Database["public"]["Enums"]["campaign_trigger"];
          config?: Json;
          channel?: Database["public"]["Enums"]["message_channel"];
          fallback_channel?: Database["public"]["Enums"]["message_channel"] | null;
          template_key: string;
          cooldown_days?: number;
          skip_if_future_booking?: boolean;
          skip_if_lapsed_beyond_days?: number | null;
          min_churn_risk?: number;
          respect_quiet_hours?: boolean;
          daily_send_cap?: number | null;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          key?: string;
          name?: string;
          description?: string | null;
          trigger_type?: Database["public"]["Enums"]["campaign_trigger"];
          config?: Json;
          channel?: Database["public"]["Enums"]["message_channel"];
          fallback_channel?: Database["public"]["Enums"]["message_channel"] | null;
          template_key?: string;
          cooldown_days?: number;
          skip_if_future_booking?: boolean;
          skip_if_lapsed_beyond_days?: number | null;
          min_churn_risk?: number;
          respect_quiet_hours?: boolean;
          daily_send_cap?: number | null;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      client_files: {
        Row: {
          id: string;
          client_id: string;
          business_id: string;
          appointment_id: string | null;
          storage_path: string;
          file_name: string | null;
          mime_type: string | null;
          size_bytes: number | null;
          kind: string;
          caption: string | null;
          client_visible: boolean;
          uploaded_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          client_id: string;
          business_id: string;
          appointment_id?: string | null;
          storage_path: string;
          file_name?: string | null;
          mime_type?: string | null;
          size_bytes?: number | null;
          kind?: string;
          caption?: string | null;
          client_visible?: boolean;
          uploaded_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          client_id?: string;
          business_id?: string;
          appointment_id?: string | null;
          storage_path?: string;
          file_name?: string | null;
          mime_type?: string | null;
          size_bytes?: number | null;
          kind?: string;
          caption?: string | null;
          client_visible?: boolean;
          uploaded_by?: string | null;
          created_at?: string;
        };
      };
      client_metrics: {
        Row: {
          client_id: string;
          business_id: string;
          visit_count: number;
          completed_count: number;
          cancelled_count: number;
          late_cancel_count: number;
          no_show_count: number;
          reschedule_count: number;
          lifetime_value_cents: number;
          service_revenue_cents: number;
          retail_revenue_cents: number;
          membership_revenue_cents: number;
          tip_cents: number;
          avg_ticket_cents: number;
          spend_90d_cents: number;
          spend_365d_cents: number;
          first_visit_at: string | null;
          last_visit_at: string | null;
          avg_days_between_visits: number | null;
          next_expected_at: string | null;
          lapse_at: string | null;
          has_future_booking: boolean;
          next_appointment_at: string | null;
          no_show_risk: number;
          churn_risk: number;
          rebook_rate: number;
          loyalty_points: number;
          loyalty_tier: string;
          lifecycle: Database["public"]["Enums"]["client_lifecycle"];
          computed_at: string;
        };
        Insert: {
          client_id: string;
          business_id: string;
          visit_count?: number;
          completed_count?: number;
          cancelled_count?: number;
          late_cancel_count?: number;
          no_show_count?: number;
          reschedule_count?: number;
          lifetime_value_cents?: number;
          service_revenue_cents?: number;
          retail_revenue_cents?: number;
          membership_revenue_cents?: number;
          tip_cents?: number;
          avg_ticket_cents?: number;
          spend_90d_cents?: number;
          spend_365d_cents?: number;
          first_visit_at?: string | null;
          last_visit_at?: string | null;
          avg_days_between_visits?: number | null;
          next_expected_at?: string | null;
          lapse_at?: string | null;
          has_future_booking?: boolean;
          next_appointment_at?: string | null;
          no_show_risk?: number;
          churn_risk?: number;
          rebook_rate?: number;
          loyalty_points?: number;
          loyalty_tier?: string;
          lifecycle?: Database["public"]["Enums"]["client_lifecycle"];
          computed_at?: string;
        };
        Update: {
          client_id?: string;
          business_id?: string;
          visit_count?: number;
          completed_count?: number;
          cancelled_count?: number;
          late_cancel_count?: number;
          no_show_count?: number;
          reschedule_count?: number;
          lifetime_value_cents?: number;
          service_revenue_cents?: number;
          retail_revenue_cents?: number;
          membership_revenue_cents?: number;
          tip_cents?: number;
          avg_ticket_cents?: number;
          spend_90d_cents?: number;
          spend_365d_cents?: number;
          first_visit_at?: string | null;
          last_visit_at?: string | null;
          avg_days_between_visits?: number | null;
          next_expected_at?: string | null;
          lapse_at?: string | null;
          has_future_booking?: boolean;
          next_appointment_at?: string | null;
          no_show_risk?: number;
          churn_risk?: number;
          rebook_rate?: number;
          loyalty_points?: number;
          loyalty_tier?: string;
          lifecycle?: Database["public"]["Enums"]["client_lifecycle"];
          computed_at?: string;
        };
      };
      client_notes: {
        Row: {
          id: string;
          client_id: string;
          business_id: string;
          staff_id: string | null;
          appointment_id: string | null;
          kind: Database["public"]["Enums"]["note_kind"];
          body: string;
          structured: Json;
          client_visible: boolean;
          pinned: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          client_id: string;
          business_id: string;
          staff_id?: string | null;
          appointment_id?: string | null;
          kind?: Database["public"]["Enums"]["note_kind"];
          body: string;
          structured?: Json;
          client_visible?: boolean;
          pinned?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          client_id?: string;
          business_id?: string;
          staff_id?: string | null;
          appointment_id?: string | null;
          kind?: Database["public"]["Enums"]["note_kind"];
          body?: string;
          structured?: Json;
          client_visible?: boolean;
          pinned?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      client_packages: {
        Row: {
          id: string;
          business_id: string;
          client_id: string;
          package_id: string;
          name_snapshot: string;
          total_quantity: number;
          remaining_quantity: number;
          price_paid_cents: number;
          purchased_at: string;
          expires_at: string | null;
          expiry_warned_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          client_id: string;
          package_id: string;
          name_snapshot: string;
          total_quantity: number;
          remaining_quantity: number;
          price_paid_cents?: number;
          purchased_at?: string;
          expires_at?: string | null;
          expiry_warned_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          client_id?: string;
          package_id?: string;
          name_snapshot?: string;
          total_quantity?: number;
          remaining_quantity?: number;
          price_paid_cents?: number;
          purchased_at?: string;
          expires_at?: string | null;
          expiry_warned_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      clients: {
        Row: {
          id: string;
          business_id: string;
          user_id: string | null;
          first_name: string;
          last_name: string | null;
          email: string | null;
          phone: string | null;
          birthday: string | null;
          pronouns: string | null;
          preferred_staff_id: string | null;
          preferred_location_id: string | null;
          preferred_time_note: string | null;
          marketing_opt_in: boolean;
          sms_opt_in: boolean;
          email_opt_in: boolean;
          opted_out_at: string | null;
          stripe_customer_id: string | null;
          default_payment_method_id: string | null;
          has_card_on_file: boolean;
          tags: string[];
          source: string | null;
          referred_by_client_id: string | null;
          referral_code: string | null;
          alert_note: string | null;
          archived_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          user_id?: string | null;
          first_name: string;
          last_name?: string | null;
          email?: string | null;
          phone?: string | null;
          birthday?: string | null;
          pronouns?: string | null;
          preferred_staff_id?: string | null;
          preferred_location_id?: string | null;
          preferred_time_note?: string | null;
          marketing_opt_in?: boolean;
          sms_opt_in?: boolean;
          email_opt_in?: boolean;
          opted_out_at?: string | null;
          stripe_customer_id?: string | null;
          default_payment_method_id?: string | null;
          has_card_on_file?: boolean;
          tags?: string[];
          source?: string | null;
          referred_by_client_id?: string | null;
          referral_code?: string | null;
          alert_note?: string | null;
          archived_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          user_id?: string | null;
          first_name?: string;
          last_name?: string | null;
          email?: string | null;
          phone?: string | null;
          birthday?: string | null;
          pronouns?: string | null;
          preferred_staff_id?: string | null;
          preferred_location_id?: string | null;
          preferred_time_note?: string | null;
          marketing_opt_in?: boolean;
          sms_opt_in?: boolean;
          email_opt_in?: boolean;
          opted_out_at?: string | null;
          stripe_customer_id?: string | null;
          default_payment_method_id?: string | null;
          has_card_on_file?: boolean;
          tags?: string[];
          source?: string | null;
          referred_by_client_id?: string | null;
          referral_code?: string | null;
          alert_note?: string | null;
          archived_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      form_submissions: {
        Row: {
          id: string;
          form_id: string;
          client_id: string;
          business_id: string;
          appointment_id: string | null;
          answers: Json;
          signature_data: string | null;
          signed_at: string | null;
          ip_address: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          form_id: string;
          client_id: string;
          business_id: string;
          appointment_id?: string | null;
          answers?: Json;
          signature_data?: string | null;
          signed_at?: string | null;
          ip_address?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          form_id?: string;
          client_id?: string;
          business_id?: string;
          appointment_id?: string | null;
          answers?: Json;
          signature_data?: string | null;
          signed_at?: string | null;
          ip_address?: string | null;
          created_at?: string;
        };
      };
      forms: {
        Row: {
          id: string;
          business_id: string;
          name: string;
          kind: string;
          description: string | null;
          schema: Json;
          revalidate_days: number | null;
          active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          name: string;
          kind?: string;
          description?: string | null;
          schema?: Json;
          revalidate_days?: number | null;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          name?: string;
          kind?: string;
          description?: string | null;
          schema?: Json;
          revalidate_days?: number | null;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      gift_card_transactions: {
        Row: {
          id: string;
          gift_card_id: string;
          order_id: string | null;
          delta_cents: number;
          balance_after: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          gift_card_id: string;
          order_id?: string | null;
          delta_cents: number;
          balance_after: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          gift_card_id?: string;
          order_id?: string | null;
          delta_cents?: number;
          balance_after?: number;
          created_at?: string;
        };
      };
      gift_cards: {
        Row: {
          id: string;
          business_id: string;
          code: string;
          initial_cents: number;
          balance_cents: number;
          purchaser_client_id: string | null;
          recipient_name: string | null;
          recipient_email: string | null;
          message: string | null;
          deliver_at: string | null;
          delivered_at: string | null;
          expires_at: string | null;
          redeemed_by_client_id: string | null;
          active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          code: string;
          initial_cents: number;
          balance_cents: number;
          purchaser_client_id?: string | null;
          recipient_name?: string | null;
          recipient_email?: string | null;
          message?: string | null;
          deliver_at?: string | null;
          delivered_at?: string | null;
          expires_at?: string | null;
          redeemed_by_client_id?: string | null;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          code?: string;
          initial_cents?: number;
          balance_cents?: number;
          purchaser_client_id?: string | null;
          recipient_name?: string | null;
          recipient_email?: string | null;
          message?: string | null;
          deliver_at?: string | null;
          delivered_at?: string | null;
          expires_at?: string | null;
          redeemed_by_client_id?: string | null;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      locations: {
        Row: {
          id: string;
          business_id: string;
          name: string;
          slug: string;
          timezone: string | null;
          phone: string | null;
          email: string | null;
          address_line1: string | null;
          address_line2: string | null;
          city: string | null;
          region: string | null;
          postal_code: string | null;
          country: string;
          latitude: number | null;
          longitude: number | null;
          hours: Json;
          hour_overrides: Json;
          booking_enabled: boolean;
          sort_order: number;
          active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          name: string;
          slug: string;
          timezone?: string | null;
          phone?: string | null;
          email?: string | null;
          address_line1?: string | null;
          address_line2?: string | null;
          city?: string | null;
          region?: string | null;
          postal_code?: string | null;
          country?: string;
          latitude?: number | null;
          longitude?: number | null;
          hours?: Json;
          hour_overrides?: Json;
          booking_enabled?: boolean;
          sort_order?: number;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          name?: string;
          slug?: string;
          timezone?: string | null;
          phone?: string | null;
          email?: string | null;
          address_line1?: string | null;
          address_line2?: string | null;
          city?: string | null;
          region?: string | null;
          postal_code?: string | null;
          country?: string;
          latitude?: number | null;
          longitude?: number | null;
          hours?: Json;
          hour_overrides?: Json;
          booking_enabled?: boolean;
          sort_order?: number;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      loyalty_transactions: {
        Row: {
          id: string;
          business_id: string;
          client_id: string;
          points: number;
          balance_after: number;
          reason: string;
          order_id: string | null;
          appointment_id: string | null;
          expires_at: string | null;
          note: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          client_id: string;
          points: number;
          balance_after: number;
          reason: string;
          order_id?: string | null;
          appointment_id?: string | null;
          expires_at?: string | null;
          note?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          client_id?: string;
          points?: number;
          balance_after?: number;
          reason?: string;
          order_id?: string | null;
          appointment_id?: string | null;
          expires_at?: string | null;
          note?: string | null;
          created_at?: string;
        };
      };
      membership_credit_ledger: {
        Row: {
          id: string;
          membership_id: string;
          business_id: string;
          delta: number;
          balance_after: number;
          reason: Database["public"]["Enums"]["ledger_reason"];
          appointment_id: string | null;
          expires_at: string | null;
          note: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          membership_id: string;
          business_id: string;
          delta: number;
          balance_after: number;
          reason: Database["public"]["Enums"]["ledger_reason"];
          appointment_id?: string | null;
          expires_at?: string | null;
          note?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          membership_id?: string;
          business_id?: string;
          delta?: number;
          balance_after?: number;
          reason?: Database["public"]["Enums"]["ledger_reason"];
          appointment_id?: string | null;
          expires_at?: string | null;
          note?: string | null;
          created_at?: string;
        };
      };
      membership_plans: {
        Row: {
          id: string;
          business_id: string;
          name: string;
          slug: string;
          description: string | null;
          pitch: string | null;
          price_cents: number;
          billing_interval: string;
          interval_count: number;
          setup_fee_cents: number;
          trial_days: number;
          included_credits: number;
          credit_service_ids: string[];
          discount_pct: number;
          retail_discount_pct: number;
          perks: Json;
          waives_deposits: boolean;
          priority_booking_days: number;
          commitment_months: number;
          rollover_periods: number;
          max_banked_credits: number;
          allow_pause: boolean;
          stripe_product_id: string | null;
          stripe_price_id: string | null;
          max_members: number | null;
          active: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          name: string;
          slug: string;
          description?: string | null;
          pitch?: string | null;
          price_cents: number;
          billing_interval?: string;
          interval_count?: number;
          setup_fee_cents?: number;
          trial_days?: number;
          included_credits?: number;
          credit_service_ids?: string[];
          discount_pct?: number;
          retail_discount_pct?: number;
          perks?: Json;
          waives_deposits?: boolean;
          priority_booking_days?: number;
          commitment_months?: number;
          rollover_periods?: number;
          max_banked_credits?: number;
          allow_pause?: boolean;
          stripe_product_id?: string | null;
          stripe_price_id?: string | null;
          max_members?: number | null;
          active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          pitch?: string | null;
          price_cents?: number;
          billing_interval?: string;
          interval_count?: number;
          setup_fee_cents?: number;
          trial_days?: number;
          included_credits?: number;
          credit_service_ids?: string[];
          discount_pct?: number;
          retail_discount_pct?: number;
          perks?: Json;
          waives_deposits?: boolean;
          priority_booking_days?: number;
          commitment_months?: number;
          rollover_periods?: number;
          max_banked_credits?: number;
          allow_pause?: boolean;
          stripe_product_id?: string | null;
          stripe_price_id?: string | null;
          max_members?: number | null;
          active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      memberships: {
        Row: {
          id: string;
          business_id: string;
          client_id: string;
          plan_id: string;
          status: Database["public"]["Enums"]["membership_status"];
          stripe_subscription_id: string | null;
          stripe_customer_id: string | null;
          current_period_start: string | null;
          current_period_end: string | null;
          credits_balance: number;
          credits_used_this_period: number;
          started_at: string;
          commitment_ends_at: string | null;
          paused_at: string | null;
          paused_until: string | null;
          pauses_used_this_year: number;
          cancel_at_period_end: boolean;
          cancellation_requested_at: string | null;
          cancellation_reason: string | null;
          cancelled_at: string | null;
          save_offer_accepted: string | null;
          save_offers_shown: string[];
          past_due_since: string | null;
          dunning_attempts: number;
          last_payment_failed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          client_id: string;
          plan_id: string;
          status?: Database["public"]["Enums"]["membership_status"];
          stripe_subscription_id?: string | null;
          stripe_customer_id?: string | null;
          current_period_start?: string | null;
          current_period_end?: string | null;
          credits_balance?: number;
          credits_used_this_period?: number;
          started_at?: string;
          commitment_ends_at?: string | null;
          paused_at?: string | null;
          paused_until?: string | null;
          pauses_used_this_year?: number;
          cancel_at_period_end?: boolean;
          cancellation_requested_at?: string | null;
          cancellation_reason?: string | null;
          cancelled_at?: string | null;
          save_offer_accepted?: string | null;
          save_offers_shown?: string[];
          past_due_since?: string | null;
          dunning_attempts?: number;
          last_payment_failed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          client_id?: string;
          plan_id?: string;
          status?: Database["public"]["Enums"]["membership_status"];
          stripe_subscription_id?: string | null;
          stripe_customer_id?: string | null;
          current_period_start?: string | null;
          current_period_end?: string | null;
          credits_balance?: number;
          credits_used_this_period?: number;
          started_at?: string;
          commitment_ends_at?: string | null;
          paused_at?: string | null;
          paused_until?: string | null;
          pauses_used_this_year?: number;
          cancel_at_period_end?: boolean;
          cancellation_requested_at?: string | null;
          cancellation_reason?: string | null;
          cancelled_at?: string | null;
          save_offer_accepted?: string | null;
          save_offers_shown?: string[];
          past_due_since?: string | null;
          dunning_attempts?: number;
          last_payment_failed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      message_templates: {
        Row: {
          id: string;
          business_id: string;
          key: string;
          name: string;
          channel: Database["public"]["Enums"]["message_channel"];
          subject: string | null;
          body: string;
          variables: string[];
          active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          key: string;
          name: string;
          channel: Database["public"]["Enums"]["message_channel"];
          subject?: string | null;
          body: string;
          variables?: string[];
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          key?: string;
          name?: string;
          channel?: Database["public"]["Enums"]["message_channel"];
          subject?: string | null;
          body?: string;
          variables?: string[];
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      offers: {
        Row: {
          id: string;
          business_id: string;
          client_id: string | null;
          code: string;
          label: string;
          kind: string;
          value: number;
          service_ids: string[];
          campaign_id: string | null;
          source: string | null;
          max_redemptions: number;
          redemption_count: number;
          redeemed_at: string | null;
          redeemed_order_id: string | null;
          starts_at: string;
          expires_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          client_id?: string | null;
          code: string;
          label: string;
          kind: string;
          value?: number;
          service_ids?: string[];
          campaign_id?: string | null;
          source?: string | null;
          max_redemptions?: number;
          redemption_count?: number;
          redeemed_at?: string | null;
          redeemed_order_id?: string | null;
          starts_at?: string;
          expires_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          client_id?: string | null;
          code?: string;
          label?: string;
          kind?: string;
          value?: number;
          service_ids?: string[];
          campaign_id?: string | null;
          source?: string | null;
          max_redemptions?: number;
          redemption_count?: number;
          redeemed_at?: string | null;
          redeemed_order_id?: string | null;
          starts_at?: string;
          expires_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      order_items: {
        Row: {
          id: string;
          order_id: string;
          business_id: string;
          kind: Database["public"]["Enums"]["order_item_kind"];
          reference_id: string | null;
          name_snapshot: string;
          quantity: number;
          unit_price_cents: number;
          total_cents: number;
          cost_cents: number;
          from_upsell: boolean;
          staff_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          order_id: string;
          business_id: string;
          kind: Database["public"]["Enums"]["order_item_kind"];
          reference_id?: string | null;
          name_snapshot: string;
          quantity?: number;
          unit_price_cents?: number;
          total_cents?: number;
          cost_cents?: number;
          from_upsell?: boolean;
          staff_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          order_id?: string;
          business_id?: string;
          kind?: Database["public"]["Enums"]["order_item_kind"];
          reference_id?: string | null;
          name_snapshot?: string;
          quantity?: number;
          unit_price_cents?: number;
          total_cents?: number;
          cost_cents?: number;
          from_upsell?: boolean;
          staff_id?: string | null;
          created_at?: string;
        };
      };
      orders: {
        Row: {
          id: string;
          business_id: string;
          client_id: string | null;
          appointment_id: string | null;
          location_id: string | null;
          staff_id: string | null;
          number: number;
          status: Database["public"]["Enums"]["order_status"];
          subtotal_cents: number;
          discount_cents: number;
          tax_cents: number;
          tip_cents: number;
          total_cents: number;
          refunded_cents: number;
          membership_credit_applied: number;
          package_credit_applied: number;
          gift_card_cents_applied: number;
          loyalty_points_applied: number;
          currency: string;
          stripe_payment_intent_id: string | null;
          stripe_checkout_session_id: string | null;
          closed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          client_id?: string | null;
          appointment_id?: string | null;
          location_id?: string | null;
          staff_id?: string | null;
          number?: number;
          status?: Database["public"]["Enums"]["order_status"];
          subtotal_cents?: number;
          discount_cents?: number;
          tax_cents?: number;
          tip_cents?: number;
          total_cents?: number;
          refunded_cents?: number;
          membership_credit_applied?: number;
          package_credit_applied?: number;
          gift_card_cents_applied?: number;
          loyalty_points_applied?: number;
          currency?: string;
          stripe_payment_intent_id?: string | null;
          stripe_checkout_session_id?: string | null;
          closed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          client_id?: string | null;
          appointment_id?: string | null;
          location_id?: string | null;
          staff_id?: string | null;
          number?: number;
          status?: Database["public"]["Enums"]["order_status"];
          subtotal_cents?: number;
          discount_cents?: number;
          tax_cents?: number;
          tip_cents?: number;
          total_cents?: number;
          refunded_cents?: number;
          membership_credit_applied?: number;
          package_credit_applied?: number;
          gift_card_cents_applied?: number;
          loyalty_points_applied?: number;
          currency?: string;
          stripe_payment_intent_id?: string | null;
          stripe_checkout_session_id?: string | null;
          closed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      packages: {
        Row: {
          id: string;
          business_id: string;
          name: string;
          description: string | null;
          service_id: string | null;
          valid_service_ids: string[];
          quantity: number;
          price_cents: number;
          compare_at_cents: number | null;
          expires_days: number | null;
          transferable: boolean;
          stripe_price_id: string | null;
          active: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          name: string;
          description?: string | null;
          service_id?: string | null;
          valid_service_ids?: string[];
          quantity: number;
          price_cents: number;
          compare_at_cents?: number | null;
          expires_days?: number | null;
          transferable?: boolean;
          stripe_price_id?: string | null;
          active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          name?: string;
          description?: string | null;
          service_id?: string | null;
          valid_service_ids?: string[];
          quantity?: number;
          price_cents?: number;
          compare_at_cents?: number | null;
          expires_days?: number | null;
          transferable?: boolean;
          stripe_price_id?: string | null;
          active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      payments: {
        Row: {
          id: string;
          business_id: string;
          order_id: string | null;
          client_id: string | null;
          appointment_id: string | null;
          membership_id: string | null;
          amount_cents: number;
          currency: string;
          status: Database["public"]["Enums"]["payment_status"];
          method: string;
          purpose: string;
          stripe_payment_intent_id: string | null;
          stripe_charge_id: string | null;
          stripe_invoice_id: string | null;
          failure_code: string | null;
          failure_message: string | null;
          refunded_cents: number;
          processed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          order_id?: string | null;
          client_id?: string | null;
          appointment_id?: string | null;
          membership_id?: string | null;
          amount_cents: number;
          currency?: string;
          status?: Database["public"]["Enums"]["payment_status"];
          method?: string;
          purpose?: string;
          stripe_payment_intent_id?: string | null;
          stripe_charge_id?: string | null;
          stripe_invoice_id?: string | null;
          failure_code?: string | null;
          failure_message?: string | null;
          refunded_cents?: number;
          processed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          order_id?: string | null;
          client_id?: string | null;
          appointment_id?: string | null;
          membership_id?: string | null;
          amount_cents?: number;
          currency?: string;
          status?: Database["public"]["Enums"]["payment_status"];
          method?: string;
          purpose?: string;
          stripe_payment_intent_id?: string | null;
          stripe_charge_id?: string | null;
          stripe_invoice_id?: string | null;
          failure_code?: string | null;
          failure_message?: string | null;
          refunded_cents?: number;
          processed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      products: {
        Row: {
          id: string;
          business_id: string;
          name: string;
          sku: string | null;
          description: string | null;
          brand: string | null;
          image_url: string | null;
          price_cents: number;
          member_price_cents: number | null;
          cost_cents: number;
          taxable: boolean;
          stock_quantity: number | null;
          low_stock_threshold: number;
          replenish_days: number | null;
          active: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          name: string;
          sku?: string | null;
          description?: string | null;
          brand?: string | null;
          image_url?: string | null;
          price_cents?: number;
          member_price_cents?: number | null;
          cost_cents?: number;
          taxable?: boolean;
          stock_quantity?: number | null;
          low_stock_threshold?: number;
          replenish_days?: number | null;
          active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          name?: string;
          sku?: string | null;
          description?: string | null;
          brand?: string | null;
          image_url?: string | null;
          price_cents?: number;
          member_price_cents?: number | null;
          cost_cents?: number;
          taxable?: boolean;
          stock_quantity?: number | null;
          low_stock_threshold?: number;
          replenish_days?: number | null;
          active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      referrals: {
        Row: {
          id: string;
          business_id: string;
          referrer_client_id: string;
          referee_client_id: string | null;
          referee_email: string | null;
          referee_phone: string | null;
          code: string;
          status: string;
          referrer_reward_cents: number;
          referee_reward_cents: number;
          qualifying_appointment_id: string | null;
          rewarded_at: string | null;
          expires_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          referrer_client_id: string;
          referee_client_id?: string | null;
          referee_email?: string | null;
          referee_phone?: string | null;
          code: string;
          status?: string;
          referrer_reward_cents?: number;
          referee_reward_cents?: number;
          qualifying_appointment_id?: string | null;
          rewarded_at?: string | null;
          expires_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          referrer_client_id?: string;
          referee_client_id?: string | null;
          referee_email?: string | null;
          referee_phone?: string | null;
          code?: string;
          status?: string;
          referrer_reward_cents?: number;
          referee_reward_cents?: number;
          qualifying_appointment_id?: string | null;
          rewarded_at?: string | null;
          expires_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      reviews: {
        Row: {
          id: string;
          business_id: string;
          client_id: string;
          appointment_id: string | null;
          staff_id: string | null;
          rating: number | null;
          body: string | null;
          routed_public: boolean;
          needs_followup: boolean;
          followed_up_at: string | null;
          followup_note: string | null;
          requested_at: string | null;
          submitted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          client_id: string;
          appointment_id?: string | null;
          staff_id?: string | null;
          rating?: number | null;
          body?: string | null;
          routed_public?: boolean;
          needs_followup?: boolean;
          followed_up_at?: string | null;
          followup_note?: string | null;
          requested_at?: string | null;
          submitted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          client_id?: string;
          appointment_id?: string | null;
          staff_id?: string | null;
          rating?: number | null;
          body?: string | null;
          routed_public?: boolean;
          needs_followup?: boolean;
          followed_up_at?: string | null;
          followup_note?: string | null;
          requested_at?: string | null;
          submitted_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      rooms: {
        Row: {
          id: string;
          business_id: string;
          location_id: string;
          name: string;
          kind: string;
          capacity: number;
          active: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          location_id: string;
          name: string;
          kind?: string;
          capacity?: number;
          active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          location_id?: string;
          name?: string;
          kind?: string;
          capacity?: number;
          active?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      service_addons: {
        Row: {
          service_id: string;
          addon_id: string;
          is_recommended: boolean;
          sort_order: number;
        };
        Insert: {
          service_id: string;
          addon_id: string;
          is_recommended?: boolean;
          sort_order?: number;
        };
        Update: {
          service_id?: string;
          addon_id?: string;
          is_recommended?: boolean;
          sort_order?: number;
        };
      };
      service_categories: {
        Row: {
          id: string;
          business_id: string;
          name: string;
          description: string | null;
          sort_order: number;
          active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          name: string;
          description?: string | null;
          sort_order?: number;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          name?: string;
          description?: string | null;
          sort_order?: number;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      service_products: {
        Row: {
          service_id: string;
          product_id: string;
          sort_order: number;
        };
        Insert: {
          service_id: string;
          product_id: string;
          sort_order?: number;
        };
        Update: {
          service_id?: string;
          product_id?: string;
          sort_order?: number;
        };
      };
      service_staff: {
        Row: {
          service_id: string;
          staff_id: string;
          price_override_cents: number | null;
          duration_override_min: number | null;
        };
        Insert: {
          service_id: string;
          staff_id: string;
          price_override_cents?: number | null;
          duration_override_min?: number | null;
        };
        Update: {
          service_id?: string;
          staff_id?: string;
          price_override_cents?: number | null;
          duration_override_min?: number | null;
        };
      };
      services: {
        Row: {
          id: string;
          business_id: string;
          category_id: string | null;
          name: string;
          slug: string;
          description: string | null;
          image_url: string | null;
          duration_min: number;
          processing_time_min: number;
          finish_time_min: number;
          buffer_before_min: number | null;
          buffer_after_min: number | null;
          price_cents: number;
          member_price_cents: number | null;
          price_type: string;
          cost_cents: number;
          taxable: boolean;
          deposit_mode: Database["public"]["Enums"]["deposit_mode"];
          deposit_flat_cents: number;
          deposit_percent: number;
          rebook_interval_days: number;
          rebook_window_days: number;
          online_bookable: boolean;
          requires_consultation: boolean;
          requires_intake_form: boolean;
          requires_consent_form: boolean;
          new_clients_only: boolean;
          existing_clients_only: boolean;
          required_room_kind: string | null;
          releases_room_in_gap: boolean;
          max_per_day: number | null;
          sort_order: number;
          active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          category_id?: string | null;
          name: string;
          slug: string;
          description?: string | null;
          image_url?: string | null;
          duration_min: number;
          processing_time_min?: number;
          finish_time_min?: number;
          buffer_before_min?: number | null;
          buffer_after_min?: number | null;
          price_cents?: number;
          member_price_cents?: number | null;
          price_type?: string;
          cost_cents?: number;
          taxable?: boolean;
          deposit_mode?: Database["public"]["Enums"]["deposit_mode"];
          deposit_flat_cents?: number;
          deposit_percent?: number;
          rebook_interval_days?: number;
          rebook_window_days?: number;
          online_bookable?: boolean;
          requires_consultation?: boolean;
          requires_intake_form?: boolean;
          requires_consent_form?: boolean;
          new_clients_only?: boolean;
          existing_clients_only?: boolean;
          required_room_kind?: string | null;
          releases_room_in_gap?: boolean;
          max_per_day?: number | null;
          sort_order?: number;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          category_id?: string | null;
          name?: string;
          slug?: string;
          description?: string | null;
          image_url?: string | null;
          duration_min?: number;
          processing_time_min?: number;
          finish_time_min?: number;
          buffer_before_min?: number | null;
          buffer_after_min?: number | null;
          price_cents?: number;
          member_price_cents?: number | null;
          price_type?: string;
          cost_cents?: number;
          taxable?: boolean;
          deposit_mode?: Database["public"]["Enums"]["deposit_mode"];
          deposit_flat_cents?: number;
          deposit_percent?: number;
          rebook_interval_days?: number;
          rebook_window_days?: number;
          online_bookable?: boolean;
          requires_consultation?: boolean;
          requires_intake_form?: boolean;
          requires_consent_form?: boolean;
          new_clients_only?: boolean;
          existing_clients_only?: boolean;
          required_room_kind?: string | null;
          releases_room_in_gap?: boolean;
          max_per_day?: number | null;
          sort_order?: number;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      staff: {
        Row: {
          id: string;
          business_id: string;
          user_id: string | null;
          role: Database["public"]["Enums"]["staff_role"];
          display_name: string;
          title: string | null;
          bio: string | null;
          avatar_url: string | null;
          email: string | null;
          phone: string | null;
          bookable: boolean;
          accepts_new_clients: boolean;
          price_multiplier: number;
          commission_rate: number;
          buffer_after_min: number | null;
          color: string | null;
          sort_order: number;
          active: boolean;
          hired_on: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          user_id?: string | null;
          role?: Database["public"]["Enums"]["staff_role"];
          display_name: string;
          title?: string | null;
          bio?: string | null;
          avatar_url?: string | null;
          email?: string | null;
          phone?: string | null;
          bookable?: boolean;
          accepts_new_clients?: boolean;
          price_multiplier?: number;
          commission_rate?: number;
          buffer_after_min?: number | null;
          color?: string | null;
          sort_order?: number;
          active?: boolean;
          hired_on?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          user_id?: string | null;
          role?: Database["public"]["Enums"]["staff_role"];
          display_name?: string;
          title?: string | null;
          bio?: string | null;
          avatar_url?: string | null;
          email?: string | null;
          phone?: string | null;
          bookable?: boolean;
          accepts_new_clients?: boolean;
          price_multiplier?: number;
          commission_rate?: number;
          buffer_after_min?: number | null;
          color?: string | null;
          sort_order?: number;
          active?: boolean;
          hired_on?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      staff_locations: {
        Row: {
          staff_id: string;
          location_id: string;
        };
        Insert: {
          staff_id: string;
          location_id: string;
        };
        Update: {
          staff_id?: string;
          location_id?: string;
        };
      };
      staff_schedules: {
        Row: {
          id: string;
          staff_id: string;
          location_id: string;
          weekday: number;
          start_time: string;
          end_time: string;
          effective_from: string;
          effective_to: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          staff_id: string;
          location_id: string;
          weekday: number;
          start_time: string;
          end_time: string;
          effective_from?: string;
          effective_to?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          staff_id?: string;
          location_id?: string;
          weekday?: number;
          start_time?: string;
          end_time?: string;
          effective_from?: string;
          effective_to?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      staff_time_off: {
        Row: {
          id: string;
          staff_id: string;
          starts_at: string;
          ends_at: string;
          reason: string | null;
          all_day: boolean;
          recurrence: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          staff_id: string;
          starts_at: string;
          ends_at: string;
          reason?: string | null;
          all_day?: boolean;
          recurrence?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          staff_id?: string;
          starts_at?: string;
          ends_at?: string;
          reason?: string | null;
          all_day?: boolean;
          recurrence?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      waitlist_entries: {
        Row: {
          id: string;
          business_id: string;
          client_id: string;
          service_id: string;
          location_id: string | null;
          staff_id: string | null;
          window_start: string;
          window_end: string;
          preferred_weekdays: number[];
          earliest_time: string | null;
          latest_time: string | null;
          status: Database["public"]["Enums"]["waitlist_status"];
          priority: number;
          offered_appointment_slot: Json | null;
          offered_at: string | null;
          offer_expires_at: string | null;
          claimed_at: string | null;
          fulfilled_appointment_id: string | null;
          notify_channel: Database["public"]["Enums"]["message_channel"];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          client_id: string;
          service_id: string;
          location_id?: string | null;
          staff_id?: string | null;
          window_start: string;
          window_end: string;
          preferred_weekdays?: number[];
          earliest_time?: string | null;
          latest_time?: string | null;
          status?: Database["public"]["Enums"]["waitlist_status"];
          priority?: number;
          offered_appointment_slot?: Json | null;
          offered_at?: string | null;
          offer_expires_at?: string | null;
          claimed_at?: string | null;
          fulfilled_appointment_id?: string | null;
          notify_channel?: Database["public"]["Enums"]["message_channel"];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          client_id?: string;
          service_id?: string;
          location_id?: string | null;
          staff_id?: string | null;
          window_start?: string;
          window_end?: string;
          preferred_weekdays?: number[];
          earliest_time?: string | null;
          latest_time?: string | null;
          status?: Database["public"]["Enums"]["waitlist_status"];
          priority?: number;
          offered_appointment_slot?: Json | null;
          offered_at?: string | null;
          offer_expires_at?: string | null;
          claimed_at?: string | null;
          fulfilled_appointment_id?: string | null;
          notify_channel?: Database["public"]["Enums"]["message_channel"];
          created_at?: string;
          updated_at?: string;
        };
      };
      webhook_events: {
        Row: {
          id: string;
          provider: string;
          type: string;
          payload: Json | null;
          processed_at: string | null;
          error: string | null;
          received_at: string;
        };
        Insert: {
          id: string;
          provider?: string;
          type: string;
          payload?: Json | null;
          processed_at?: string | null;
          error?: string | null;
          received_at?: string;
        };
        Update: {
          id?: string;
          provider?: string;
          type?: string;
          payload?: Json | null;
          processed_at?: string | null;
          error?: string | null;
          received_at?: string;
        };
      };
    };
    Views: {
      v_attendance: {
        Row: {
          business_id: string | null;
          month: string | null;
          total_booked: number | null;
          completed: number | null;
          cancelled: number | null;
          late_cancelled: number | null;
          no_shows: number | null;
          rescheduled: number | null;
          no_show_rate: number | null;
          cancellation_rate: number | null;
          lost_revenue_cents: number | null;
          recovered_fee_cents: number | null;
        };
      };
      v_average_ticket: {
        Row: {
          business_id: string | null;
          month: string | null;
          ticket_count: number | null;
          avg_ticket_cents: number | null;
          avg_ticket_with_addon_cents: number | null;
          avg_ticket_no_addon_cents: number | null;
          addon_attach_rate: number | null;
          retail_attach_rate: number | null;
          revenue_cents: number | null;
          tips_cents: number | null;
        };
      };
      v_campaign_performance: {
        Row: {
          business_id: string | null;
          campaign_id: string | null;
          campaign_name: string | null;
          trigger_type: Database["public"]["Enums"]["campaign_trigger"] | null;
          channel: Database["public"]["Enums"]["message_channel"] | null;
          month: string | null;
          sent: number | null;
          failed: number | null;
          skipped: number | null;
          opened: number | null;
          clicked: number | null;
          converted: number | null;
          conversion_rate: number | null;
          revenue_cents: number | null;
        };
      };
      v_clients_due: {
        Row: {
          client_id: string | null;
          business_id: string | null;
          first_name: string | null;
          last_name: string | null;
          email: string | null;
          phone: string | null;
          preferred_staff_id: string | null;
          lifecycle: Database["public"]["Enums"]["client_lifecycle"] | null;
          last_visit_at: string | null;
          next_expected_at: string | null;
          lapse_at: string | null;
          churn_risk: number | null;
          no_show_risk: number | null;
          lifetime_value_cents: number | null;
          avg_ticket_cents: number | null;
          avg_days_between_visits: number | null;
          visit_count: number | null;
          days_since_visit: number | null;
          days_overdue: number | null;
          priority_score: number | null;
        };
      };
      v_membership_movement: {
        Row: {
          business_id: string | null;
          month: string | null;
          new_members: number | null;
          churned_members: number | null;
          active_members: number | null;
        };
      };
      v_mrr: {
        Row: {
          business_id: string | null;
          active_members: number | null;
          past_due_members: number | null;
          paused_members: number | null;
          cancelling_members: number | null;
          mrr_cents: number | null;
          paused_mrr_cents: number | null;
          at_risk_mrr_cents: number | null;
        };
      };
      v_rebooking_rate: {
        Row: {
          business_id: string | null;
          month: string | null;
          completed_visits: number | null;
          rebooked_at_visit: number | null;
          left_with_next_booked: number | null;
          rebook_prompt_rate: number | null;
          rebook_rate: number | null;
        };
      };
      v_retention_cohorts: {
        Row: {
          business_id: string | null;
          cohort_month: string | null;
          visit_month: string | null;
          month_offset: number | null;
          retained_clients: number | null;
          cohort_size: number | null;
        };
      };
      v_staff_performance: {
        Row: {
          staff_id: string | null;
          business_id: string | null;
          display_name: string | null;
          month: string | null;
          visits: number | null;
          unique_clients: number | null;
          revenue_cents: number | null;
          avg_ticket_cents: number | null;
          tips_cents: number | null;
          rebooked: number | null;
          rebook_rate: number | null;
          addon_attach_rate: number | null;
          retail_attach_rate: number | null;
        };
      };
      v_utilization: {
        Row: {
          business_id: string | null;
          staff_id: string | null;
          week: string | null;
          booked_minutes: number | null;
          available_minutes: number | null;
          utilization_pct: number | null;
          open_minutes: number | null;
        };
      };
    };
    Enums: {
      appointment_status: 'requested' | 'booked' | 'confirmed' | 'checked_in' | 'in_progress' | 'completed' | 'cancelled' | 'no_show' | 'rescheduled';
      booking_source: 'online' | 'admin' | 'phone' | 'walk_in' | 'rebook_prompt' | 'waitlist' | 'campaign' | 'membership_auto' | 'import';
      campaign_trigger: 'appointment_booked' | 'appointment_reminder' | 'appointment_completed' | 'rebooking_nudge' | 'lapse_winback' | 'birthday' | 'membership_welcome' | 'membership_dunning' | 'membership_cancel_save' | 'membership_credit_expiring' | 'package_expiring' | 'review_request' | 'waitlist_offer' | 'no_show_followup' | 'first_visit_followup' | 'referral_invite' | 'manual';
      client_lifecycle: 'lead' | 'new' | 'active' | 'due' | 'at_risk' | 'lapsed' | 'recovered' | 'vip';
      deposit_mode: 'none' | 'flat' | 'percent' | 'full';
      ledger_reason: 'period_grant' | 'rollover' | 'redemption' | 'refund' | 'manual_adjustment' | 'expiry' | 'signup_bonus' | 'save_offer';
      membership_status: 'trialing' | 'active' | 'past_due' | 'paused' | 'cancelling' | 'cancelled' | 'expired';
      message_channel: 'email' | 'sms' | 'push' | 'in_app';
      note_kind: 'note' | 'formula' | 'medical' | 'preference' | 'incident' | 'consult';
      order_item_kind: 'service' | 'addon' | 'product' | 'package' | 'membership' | 'gift_card' | 'tip' | 'fee' | 'discount' | 'tax';
      order_status: 'open' | 'paid' | 'partially_refunded' | 'refunded' | 'void';
      payment_status: 'pending' | 'succeeded' | 'failed' | 'refunded' | 'disputed';
      send_status: 'scheduled' | 'sending' | 'sent' | 'delivered' | 'failed' | 'skipped' | 'cancelled';
      staff_role: 'owner' | 'manager' | 'front_desk' | 'provider' | 'read_only';
      waitlist_status: 'waiting' | 'offered' | 'claimed' | 'expired' | 'cancelled' | 'fulfilled';
    };
  };
}

// --- Convenience aliases -------------------------------------------------

type PublicSchema = Database['public'];

export type Tables<T extends keyof PublicSchema["Tables"]> =
  PublicSchema["Tables"][T]["Row"];
export type TablesInsert<T extends keyof PublicSchema["Tables"]> =
  PublicSchema["Tables"][T]["Insert"];
export type TablesUpdate<T extends keyof PublicSchema["Tables"]> =
  PublicSchema["Tables"][T]["Update"];
export type Views<T extends keyof PublicSchema["Views"]> =
  PublicSchema["Views"][T]["Row"];
export type Enums<T extends keyof PublicSchema["Enums"]> =
  PublicSchema["Enums"][T];

export type Business = Tables<'businesses'>;
export type Location = Tables<'locations'>;
export type Room = Tables<'rooms'>;
export type Staff = Tables<'staff'>;
export type StaffSchedule = Tables<'staff_schedules'>;
export type TimeOff = Tables<'staff_time_off'>;
export type Service = Tables<'services'>;
export type ServiceCategory = Tables<'service_categories'>;
export type Addon = Tables<'addons'>;
export type Product = Tables<'products'>;
export type Package = Tables<'packages'>;
export type Client = Tables<'clients'>;
export type ClientMetrics = Tables<'client_metrics'>;
export type ClientNote = Tables<'client_notes'>;
export type ClientFile = Tables<'client_files'>;
export type Appointment = Tables<'appointments'>;
export type AppointmentAddon = Tables<'appointment_addons'>;
export type WaitlistEntry = Tables<'waitlist_entries'>;
export type MembershipPlan = Tables<'membership_plans'>;
export type Membership = Tables<'memberships'>;
export type ClientPackage = Tables<'client_packages'>;
export type Order = Tables<'orders'>;
export type OrderItem = Tables<'order_items'>;
export type Payment = Tables<'payments'>;
export type GiftCard = Tables<'gift_cards'>;
export type LoyaltyTransaction = Tables<'loyalty_transactions'>;
export type Campaign = Tables<'campaigns'>;
export type CampaignSend = Tables<'campaign_sends'>;
export type MessageTemplate = Tables<'message_templates'>;
export type Review = Tables<'reviews'>;
export type Referral = Tables<'referrals'>;
export type Offer = Tables<'offers'>;
export type Form = Tables<'forms'>;
export type FormSubmission = Tables<'form_submissions'>;

export type AppointmentStatus = Enums<'appointment_status'>;
export type MembershipStatus = Enums<'membership_status'>;
export type ClientLifecycle = Enums<'client_lifecycle'>;
export type StaffRole = Enums<'staff_role'>;
export type BookingSource = Enums<'booking_source'>;
export type MessageChannel = Enums<'message_channel'>;
export type CampaignTrigger = Enums<'campaign_trigger'>;
export type SendStatus = Enums<'send_status'>;
export type OrderItemKind = Enums<'order_item_kind'>;

